export const PROBLEM_TAGS = [
  "array",
  "string",
  "linkedList",
  "stack",
  "queue",
  "hashing",
  "tree",
  "heap",
  "graph",
  "greedy",
  "dp",
  "recursion",
  "backtracking",
  "binarySearch",
  "bitManipulation",
];

export const PROBLEM_TAG_OPTIONS = [
  { value: "array", label: "Array" },
  { value: "string", label: "String" },
  { value: "linkedList", label: "Linked List" },
  { value: "stack", label: "Stack" },
  { value: "queue", label: "Queue" },
  { value: "hashing", label: "Hashing" },
  { value: "tree", label: "Tree" },
  { value: "heap", label: "Heap" },
  { value: "graph", label: "Graph" },
  { value: "greedy", label: "Greedy" },
  { value: "dp", label: "Dynamic Programming" },
  { value: "recursion", label: "Recursion" },
  { value: "backtracking", label: "Backtracking" },
  { value: "binarySearch", label: "Binary Search" },
  { value: "bitManipulation", label: "Bit Manipulation" },
];
